In [1]:
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "0,1"
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"
import warnings
warnings.filterwarnings("ignore")
import numpy as np
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import random
import pickle
import tensorflow as tf
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
import pandas as pd
import os
from sklearn.decomposition import PCA
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
import keras
import sys

Using TensorFlow backend.


In [3]:
filename = '/home/sxz/data/geolife_Data/Origin_data_Cross.pickle'
with open(filename, 'rb') as f:
    kfold_dataset2 = pickle.load(f)

In [8]:
np.shape(kfold_dataset2[1])

(441, 5)

In [13]:
Test_X = np.concatenate((kfold_dataset2[0], kfold_dataset2[2]))

In [21]:
Test_Y = np.concatenate((kfold_dataset2[1], kfold_dataset2[3]))

In [15]:
print(np.shape(Test_X))
print(np.shape(Test_Y))

(551, 1, 248, 4)
(551, 5)


In [39]:
with open('/home/sxz/data/geolife_Data/test_Data.pickle', 'wb') as f:
    pickle.dump([Test_X , Test_Y ,Test_Y_ori], f)

In [40]:
Test_Y_ori = np.zeros((len(Test_Y)))

In [41]:
print(Test_Y)

[[1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 ...
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]]


In [42]:
for i in range(len(Test_Y)):
    Test_Y_ori[i] = np.argwhere(Test_Y[i]==1)[0]

In [35]:
with open('/home/sxz/data/geolife_Data/test_Data.pickle', 'rb') as f:
    a, b, c = pickle.load(f)

In [3]:
with open('/home/sxz/data/geolife_Data/my_Trajectory_Label.pickle', 'rb') as f:
    a, b = pickle.load(f)

In [4]:
print(np.shape(b))

(113,)


In [5]:
print(a[2])

[[39.9739833333333, 116.327283333333, 39365.6413425926, 1], [39.97345, 116.327416666667, 39365.6416203704, 1], [39.9728166666667, 116.3274, 39365.6419675926, 1], [39.9724, 116.32735, 39365.6421875, 1], [39.9722, 116.327383333333, 39365.6422800926, 1], [39.97195, 116.327416666667, 39365.6424189815, 1], [39.9715833333333, 116.327416666667, 39365.6426273148, 1], [39.9709166666667, 116.327483333333, 39365.642974537, 1], [39.96855, 116.3277, 39365.6442361111, 1], [39.96805, 116.327716666667, 39365.644537037, 1], [39.9675166666667, 116.327733333333, 39365.644837963, 1], [39.9673166666667, 116.327716666667, 39365.6449537037, 1], [39.967, 116.327716666667, 39365.6451041667, 1], [39.9667833333333, 116.327716666667, 39365.6452314815, 1], [39.9666, 116.327716666667, 39365.6453472222, 1], [39.9664166666667, 116.32765, 39365.6454861111, 1], [39.9663833333333, 116.326133333333, 39365.6461458333, 1], [39.9663333333333, 116.325733333333, 39365.6463657407, 1], [39.9663166666667, 116.325366666667, 39365

In [47]:
print(a[15][46184])

[400.166666666667, 116.21539, 40797.1415972222, 4]


In [51]:
import pickle
with open("/home/sxz/data/geolife_Data/my_Trajectory_Label.pickle", 'wb') as f:
    pickle.dump([a, b], f)

In [48]:
del a[15][68176]
del a[15][46184]

In [56]:
# print(a[2])
for i in range(len(b)):
    for j in range(len(b[i])):
        if( (b[i][j][0]>90)):
            print(i)
            print(j)
            print(b[i][j])
# print(np.shape(a))

In [32]:
a[15] = np.delete(a[15],[46184])

In [57]:
# print(a[2])
for i in range(len(a)):
    for j in range(len(a[i])):
        if( (a[i][j][0]>90)):
            print(i)
            print(j)
            print(a[i][j])
# print(np.shape(a))

In [12]:
with open('/home/sxz/data/geolife_Data/paper2_Trajectory_Label.pickle', 'rb') as f:
    a, b = pickle.load(f)

In [59]:
# print(a[2])
print(np.shape(a))
print(np.shape(b))
print(np.shape(a[2]))
for i in range(len(b)):
    print(np.shape(b[i]))
# print(np.shape(a))

(69,)
(113,)
(1266, 4)
(253022, 3)
(90803, 3)
(22853, 3)
(72115, 3)
(2955, 3)
(342501, 3)
(595, 3)
(2800, 3)
(84616, 3)
(1267, 3)
(8828, 3)
(21818, 3)
(36576, 3)
(47824, 3)
(148411, 3)
(239448, 3)
(8448, 3)
(9907, 3)
(37786, 3)
(84424, 3)
(251973, 3)
(11243, 3)
(20412, 3)
(267737, 3)
(35052, 3)
(56013, 3)
(485226, 3)
(48321, 3)
(173870, 3)
(6010, 3)
(81, 3)
(248217, 3)
(47166, 3)
(77910, 3)
(286, 3)
(3021, 3)
(35311, 3)
(26468, 3)
(47279, 3)
(57587, 3)
(629896, 3)
(17019, 3)
(16277, 3)
(178267, 3)
(7256, 3)
(388213, 3)
(320, 3)
(3144, 3)
(147092, 3)
(130890, 3)
(177, 3)
(4780, 3)
(15508, 3)
(96246, 3)
(24531, 3)
(2614, 3)
(43207, 3)
(41830, 3)
(45559, 3)
(352, 3)
(31830, 3)
(108607, 3)
(22978, 3)
(291182, 3)
(2794, 3)
(103734, 3)
(9076, 3)
(439397, 3)
(38744, 3)
(2500, 3)
(1360, 3)
(9784, 3)
(109046, 3)
(471437, 3)
(1057043, 3)
(84, 3)
(10790, 3)
(687, 3)
(272, 3)
(166670, 3)
(83844, 3)
(28238, 3)
(970, 3)
(4158, 3)
(89272, 3)
(339, 3)
(61020, 3)
(12490, 3)
(790, 3)
(1026179, 3)
(26348

In [5]:
filename = '/home/sxz/data/geolife_Data/my_trips_motion_features_NotFixedLength_woOutliers.pickle'
with open(filename, 'rb') as f:
    ccc, ddd = pickle.load(f)

In [7]:
print(len(ddd))
pr

11541


In [85]:
for i in range(199):
    print(len(ccc[i][0][0]))

58
396
218
609
992
661
670
700
214
43
524
73
793
318
485
1845
132
1621
263
207
102
184
33
364
268
259
69
355
212
102
330
75
25
340
64
40
172
853
127
283
149
219
462
308
693
64
1128
307
106
187
295
369
329
817
340
286
233
1520
329
352
40
82
97
35
141
79
172
183
2451
680
745
575
611
1586
34
808
474
57
137
105
368
1106
271
489
475
211
64
268
306
155
637
21
131
200
45
248
392
376
85
56
61
105
416
346
266
2214
538
327
173
263
436
132
465
921
164
958
438
353
211
2205
324
630
450
202
109
114
1463
182
248
5061
99
58
386
70
23
370
383
135
70
248
359
478
502
270
1418
23
119
130
241
165
624
234
171
451
558
107
322
1703
293
336
434
154
415
116
59
171
608
38
539
2134
153
536
67
187
89
513
338
161
609
69
46
63
43
356
660
642
579
3207
31
31
84
97
132
833
190
937
250
6126
990


In [83]:
for i in range(199):    
    print(len(ddd[i][0]))

33
43
110
414
1133
201
1025
737
82
198
188
623
1345
56
173
51
112
11351
1035
521
2000
70
897
659
780
1058
151
1048
89
277
727
1153
84
292
120
95
1195
1201
600
929
5499
137
30
864
128
403
132
351
235
450
139
24
1022
832
134
721
188
397
167
55
93
1639
507
174
227
625
281
2327
273
429
233
1267
401
386
621
241
265
1062
407
199
98
159
282
788
202
31
6801
1458
147
64
75
1554
5162
131
1013
44
236
2057
55
513
330
154
149
4534
1156
303
811
455
158
153
1996
252
583
49
457
98
170
439
158
48
350
2784
1559
329
3531
520
219
78
1131
205
41
768
435
273
269
288
532
1806
3602
1070
184
902
204
844
101
55
2571
672
432
69
71
67
75
993
366
51
316
636
130
1858
402
112
1132
635
305
513
75
100
208
852
852
144
1583
589
1133
450
503
408
237
345
5401
372
838
308
100
52
38
207
2400
2325
823
321
2610
769
1152
882
300
248
511


In [5]:
#69个有标签文件夹，182个无标签文件夹

In [50]:
sum_label = 0
sum_unlabel =0
label_num = np.zeros((5,))
for i in range(len(a)):
    sum_label += len(a[i])
    if(len(a[i]) > 0):
        for j in range(len(a[i])):
            temp = a[i][j]
            label_num_t = temp[3]
            label_num[label_num_t] += 1
for i in range(len(b)):
    sum_unlabel += len(b[i])

print(label_num)
print(sum_label)
print(sum_unlabel)

[1612493.  958183. 1283074.  759509.  873277.]
5486536
12359614


In [25]:
# 161873个有标签的点
# 24715105个无标签的点

In [3]:
filename = '/home/sxz/data/geolife_Data/paper2_trips_motion_features_temp.pickle'
with open(filename, 'rb') as f:
    trip_motion_all_user_with_label, trip_motion_all_user_wo_label = pickle.load(f)

In [4]:
print(np.shape(trip_motion_all_user_with_label))
print(np.shape(trip_motion_all_user_wo_label))

(69,)
(182,)


In [11]:
trip_motion_all_user_with_label[2][0]


(array([[ 2.75557264e+02,  1.03823976e+02,  1.50543764e+02,
          9.91047870e+01,  2.15469791e+02,  8.97966975e+01,
          8.15742901e+01,  3.35543751e+02,  6.84982945e+01,
          5.55762497e+01,  1.01821176e+02,  4.15086456e+01,
          4.80089182e+01,  4.97034926e+01,  2.03400547e+02,
          8.67993851e+02,  1.41145096e+02,  1.05848398e+02,
          9.04802697e+01,  2.57576343e+02,  5.38706367e+01,
          3.68150026e+01,  2.55221558e+02,  9.23438529e+01,
          3.05472539e+02,  2.57583011e+02,  3.59258803e+01,
          9.15709002e+01,  1.52686755e+02,  4.25702791e+02,
          2.02970587e+01,  1.01466978e+02,  5.78078797e+01,
          2.66230196e+01,  3.65113495e+01,  4.19054819e+01,
          3.91712490e+01,  2.33222175e+01,  5.59144008e+01],
        [ 3.19999937e+01,  1.60000012e+01,  2.00000015e+01,
          1.09999988e+01,  2.10000037e+01,  8.00000061e+00,
          6.99999849e+00,  4.59999994e+01,  9.99999668e+00,
          8.00000061e+00,  1.60000012e+

In [56]:
print(np.shape(trip_motion_all_user_with_label[2]))
print(np.shape(trip_motion_all_user_with_label[2][0][0]))

(1, 2)
(7, 39)


In [20]:
tmp = 0
for i in range(69):    
    print(np.shape(trip_motion_all_user_with_label[i]))
    print(trip_motion_all_user_with_label[i])
    if(len(trip_motion_all_user_with_label[i]) > 1):
        print(np.shape(trip_motion_all_user_with_label[i][0]))
    tmp += len(trip_motion_all_user_with_label[i])
#     print(np.shape(a[i]))
#     左边是一段路径(按20分钟切分)的数据，右边是所有点对应的mode
#     print("//")
# print(tmp)
#     7×39 ->960×4

(0,)
[]
(0,)
[]
(1, 2)
[(array([[ 2.75557264e+02,  1.03823976e+02,  1.50543764e+02,
         9.91047870e+01,  2.15469791e+02,  8.97966975e+01,
         8.15742901e+01,  3.35543751e+02,  6.84982945e+01,
         5.55762497e+01,  1.01821176e+02,  4.15086456e+01,
         4.80089182e+01,  4.97034926e+01,  2.03400547e+02,
         8.67993851e+02,  1.41145096e+02,  1.05848398e+02,
         9.04802697e+01,  2.57576343e+02,  5.38706367e+01,
         3.68150026e+01,  2.55221558e+02,  9.23438529e+01,
         3.05472539e+02,  2.57583011e+02,  3.59258803e+01,
         9.15709002e+01,  1.52686755e+02,  4.25702791e+02,
         2.02970587e+01,  1.01466978e+02,  5.78078797e+01,
         2.66230196e+01,  3.65113495e+01,  4.19054819e+01,
         3.91712490e+01,  2.33222175e+01,  5.59144008e+01],
       [ 3.19999937e+01,  1.60000012e+01,  2.00000015e+01,
         1.09999988e+01,  2.10000037e+01,  8.00000061e+00,
         6.99999849e+00,  4.59999994e+01,  9.99999668e+00,
         8.00000061e+00,  1.60

In [8]:

filename = '/home/sxz/data/geolife_Data/paper2_trips_motion_features_NotFixedLength_woOutliers.pickle'
with open(filename, 'rb') as f:
    cc, dd = pickle.load(f)

In [30]:
import numpy as np
sum_temp = 0
sum_label = np.zeros((5,))
sum_nodes = np.zeros((5,))
print(cc[0])
print(np.shape(cc[0]))
for i in range(len(cc)):
    sum_temp += len(cc[i][0][0])
    sum_label[cc[i][1]] += 1
    sum_nodes[cc[i][1]] += len(cc[i][0][0])
print(sum_temp)
print(sum_label)
print(sum_nodes)

(array([[ 3.32151695e+01,  2.69276840e+01,  2.22757475e+01, ...,
         1.79976487e+01,  1.34957331e+01,  1.29333883e+01],
       [ 2.99999819e+00,  2.99999819e+00,  3.00000699e+00, ...,
         2.99999819e+00,  2.99999819e+00,  2.99999819e+00],
       [ 1.89295603e-01,  1.72759077e-01,  2.15707247e-01, ...,
         2.50139099e-01,  4.16683380e-02,  4.06991063e-01],
       ...,
       [-6.98610348e-01, -5.16889717e-01,  5.33890866e-01, ...,
        -5.00213454e-01, -6.24828276e-02, -5.84864425e-01],
       [ 6.05735800e-02,  3.50260406e-01,  9.71059675e-02, ...,
         1.45910297e-01, -1.74127304e-01,  1.03349525e-01],
       [ 1.40375592e-02,  3.26639317e-02,  2.17482125e-02, ...,
         6.69404822e-03,  5.90805949e-04,  7.67226696e-03]]), 3)
(2,)
124923
[49. 19. 21. 14. 17.]
[26493.  6409.  8693.  2510. 80818.]


In [21]:
print(sum_temp)

124923
